name: Publish package to GitHub Packages
on:
  push:
    branches: [ master ]
  workflow_dispatch: {}
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Publish snapshot package
        if: github.event_name == 'workflow_dispatch'
        run: mvn --batch-mode deploy -Dmaven.resolver.transport=wagon
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish package
        if: github.event_name != 'workflow_dispatch'
        run: |
          awk '/<version>.*-SNAPSHOT<\/version>/ {gsub(/-SNAPSHOT/, "", $0)} {print}' \
            pom.xml > temp.xml && mv temp.xml pom.xml
          mvn --batch-mode deploy -Dmaven.resolver.transport=wagon
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
