name: Publish package to GitHub Packages
on:
  workflow_dispatch:
    inputs:
      plugin:
        description: 'Plugin to release'
        required: true
        type: choice
        options:
          - 'hello-world-plugin'
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Publish SNAPSHOT package
        # if not master branch, publish a snapshot
        if: github.ref != 'refs/heads/main'
        working-directory: ${{ github.event.inputs.plugin }}
        run: mvn --batch-mode deploy -Dmaven.resolver.transport=wagon
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish package
        if: github.ref == 'refs/heads/main'
        working-directory: ${{ github.event.inputs.plugin }}
        run: |
          awk '/<version>.*-SNAPSHOT<\/version>/ {gsub(/-SNAPSHOT/, "", $0)} {print}' \
            pom.xml > temp.xml && mv temp.xml pom.xml
          mvn --batch-mode deploy -Dmaven.resolver.transport=wagon
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
